### ISSUE TITLE
Error: No provider for "framework:promise"! (Resolving: framework:promise)

### ISSUE THREAD

**Issue by seanchapman** [NSAppsTeam/karma-promise#1]
Hi,

This is throwing an error when I run karma through gulp with this in my frameworks line:

frameworks: ['promise', 'systemjs', 'jspm', 'jasmine']

In my package.json devDependencies I have
"karma-promise": "^0.1.0",

**Comment by manufacturedba** [comment]
Can you post the error? Thanks!

**Comment by seanchapman** [comment]
[12:06:03] Using gulpfile gulpfile.js
[12:06:03] Starting 'test'...
[12:06:04] 'test' errored after 810 ms
[12:06:04] Error: No provider for "framework:promise"! (Resolving: framework:promise)
    at error (node_modules\di\lib\injector.js:22:12)
    at Object.get (node_modules\di\lib\injector.js:9:13)
    at Injector.get (node_modules\di\lib\injector.js:54:19)
    at node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)
    at Server._start (node_modules\karma\lib\server.js:142:21)
    at Injector.invoke (node_modules\di\lib\injector.js:75:15)
    at Server.start (node_modules\karma\lib\server.js:103:18)
    at Gulp.gulp.task (build-tasks\test.js:10:12)
    at module.exports (node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (node_modules\orchestrator\index.js:134:8)
    at AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by manufacturedba** [comment]
Do any other frameworks you have listed work?  Try running without `'promise'` listed.

Can you make sure `karma-promise` is a sibling package to `karma` in your node_modules?  That would be a clear reason why it wouldn't work.

Also try listing it as a plugin as well: http://karma-runner.github.io/1.0/config/plugins.html

**Comment by manufacturedba** [comment]
Hey @seanchapman, I'm going to close this issue as there have been no updates.  If your problem persists, feel free to re-open.  Thanks!

**Comment by rcollette** [comment]
I have this same error.  I am using webpack as well.  Our karma config is a little bit involved but here it is in case this provides any clues.

```
// Karma configuration
// Generated on Fri Apr 10 2015 17:07:21 GMT-0400 (EDT)

(() => {

  module.exports = (config) => {
    'use strict';

    const args = require('yargs').argv;
    const path = require('path');
    const wiredep = require('wiredep');
    // TODO: clean this up once we move from the gulp ci task...
    const bowerFiles = wiredep({
      bowerJson: require(path.resolve(__dirname, '../client', './bower.json')),
      directory: path.resolve(__dirname, '../client', './bower_components'),
      ignorePath: '../',
      devDependencies: true
    }).js;
    const isDist = args.dist || false;
    const component = args.component || null;
    const runCoverage = args.coverage || false;
    const port = args.port || 9877;

    const getWebpackConfig = () => {
      return require('./webpack/webpack.test.config')();
    }

    const getPort = () => {
      return port;
    }

    const getCoverageFolder = () => {
      return path.resolve('../report/coverage');
    }

    const getPreprocessors = () => {
      let preprocessors = {};
      preprocessors['app/**/en-us.json'] = ['ng-json2js'];
      preprocessors['app/**/en-ca.json'] = ['ng-json2js'];
      preprocessors['test/**/*.ts'] = ['webpack', 'sourcemap'];
      return preprocessors;
    }

    const getFiles = () => {

      let includedAssets = [
        path.resolve('./node_modules/chai-angular/chai-angular.js'),
        {
          pattern: 'app/assets/**/*.+(gif|jpg|png|svg)',
          included: false,
          served: true,
          watched: false,
          nocache: true
        },
        'app/static/js/config.js',
        'app/static/js/environment.js'
      ];

      if (isDist) {
        includedAssets = includedAssets.concat([
          'dist/app/assets/js/lib-*.js',
          'dist/app/assets/js/app-*.js',
          'app/assets/bower_resources/angular-i18n/angular-locale_en-us.js',
          'app/assets/bower_resources/angular-i18n/angular-locale_en-ca.js',
          'app/assets/bower_resources/i18n/en-us.json',
          'app/assets/bower_resources/i18n/en-ca.json',
          'karma.json.loader.js',
        ]);
      } else {
        includedAssets = includedAssets.concat(bowerFiles, [
          'app/assets/bower_resources/angular-i18n/angular-locale_en-us.js',
          'app/assets/bower_resources/angular-i18n/angular-locale_en-ca.js',
          'app/assets/bower_resources/i18n/en-us.json',
          'app/assets/bower_resources/i18n/en-ca.json',
          'karma.json.loader.js',
          'test/specs.sourceFiles.bundle.ts'
        ]);
      }

      includedAssets = includedAssets.concat('test/helpers/index.ts');

      if (component === 'modules') {
        includedAssets = includedAssets.concat('test/specs.modules.bundle.ts');
      } else if (component === 'controllers') {
        includedAssets = includedAssets.concat('test/specs.controllers.bundle.ts');
      } else if (component === 'directives') {
        includedAssets = includedAssets.concat('test/specs.directives.bundle.ts');
      } else if (component === 'services') {
        includedAssets = includedAssets.concat('test/specs.services.bundle.ts');
      } else if (component === 'filters') {
        includedAssets = includedAssets.concat('test/specs.filters.bundle.ts');
      } else if (component === 'others') {
        includedAssets = includedAssets.concat('test/specs.others.bundle.ts');
      } else {
        includedAssets = includedAssets.concat('test/specs.all.bundle.ts');
      }

      return includedAssets;
    }

    const getExcludes = () => {
      return [
        'app/assets/bower_resources/angular-i18n/!(angular-locale_en-us|angular-locale_en-ca)+(.js)',
        'bower_components/angulartics/src/angulartics.js',
        'bower_components/angulartics/src/angulartics-gtm.js.js',
        'bower_components/angulartics-segment/dist/angulartics-segment.min.js',
        'app/static/js/analytics.js'
      ];
    }

    const getReporters = () => {
      if (isDist) {
        return ['dots'];
      } else {
        if (component) {
          return ['dots', 'coverage-istanbul'];
        } else {
          return ['mocha', 'coverage-istanbul'];
        }
      }
    }

    const getCoverageIstanbulReporter = () => {
      if (isDist) {
        return {
          reports: [],
          dir: getCoverageFolder()
        };
      } else if (component) {
        return {
          reports: ['json'],
          dir: getCoverageFolder(),
          fixWebpackSourcePaths: true,
          'report-config': {
            json: {
              file: `report-json/${component}-coverage.json`,
              subdir: 'report-json'
            }
          }
        }
      } else if (runCoverage) {
        return {
          reports: ['html', 'lcov', 'cobertura', 'text-summary'],
          dir: getCoverageFolder(),
          fixWebpackSourcePaths: true
        }
      } else {
        return {
          reports: [],
          dir: getCoverageFolder()
        }
      }
    }

    const getJUnitReporter = () => {
      if (isDist) {
        return {};
      } else if (component) {
        return {
          outputDir: getCoverageFolder(),
          outputFile: `${component}-test-results.xml`,
          useBrowserName: false
        };
      } else if (runCoverage) {
        return {
          outputDir: getCoverageFolder(),
          outputFile: 'test-results.xml',
          useBrowserName: false
        };
      } else {
        return {};
      }
    }

    // This is so we can stop the 404 errors, because we load the analytics file asyncrously
    let ServeAnalyticsMiddleware = function(config) {
      return function(request, response, next) {
        if (request.url === '/static/js/analytics.js') {
          response.writeHead(200);
          return response.end('');
        } else {
          next();
        }
      };
    };

    config.set({

      // base path that will be used to resolve all patterns (eg. files, exclude)
      basePath: './',

      // frameworks to use
      // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
      frameworks: ['mocha', 'chai', 'sinon', 'chai-sinon', 'promise'],

      plugins: [
        require('karma-mocha'),
        require('karma-chai'),
        require('karma-sinon'),
        require('karma-chai-sinon'),
        require('karma-junit-reporter'),
        require('karma-mocha-reporter'),
        require('karma-phantomjs-launcher'),
        require('karma-coverage'),
        require('karma-ng-json2js-preprocessor'),
        require('karma-chrome-launcher'),
        require('karma-safari-launcher'),
        require('karma-firefox-launcher'),
        require('karma-ie-launcher'),
        require('karma-ng-html2js-preprocessor'),
        {
          'middleware:analytics': ['factory', ServeAnalyticsMiddleware]
        },
        require('karma-sourcemap-loader'),
        require('karma-webpack'),
        require('istanbul-instrumenter-loader'),
        require('karma-coverage-istanbul-reporter')
      ],

      // list of files / patterns to load in the browser
      files: getFiles(),

      // list of files to exclude
      exclude: getExcludes(),

      middleware: ['analytics'],

      proxies: {
        '/bower_components/': __dirname + '/bower_components/',
        '/assets/': __dirname + '/app/assets/'
      },

      // preprocess matching files before serving them to the browser
      // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
      preprocessors: getPreprocessors(),

      // test results reporter to use
      // possible values: 'dots', 'progress'
      // available reporters: https://npmjs.org/browse/keyword/karma-reporter
      reporters: getReporters(),

      mochaReporter: {
        output: 'autowatch'
      },

      coverageIstanbulReporter: getCoverageIstanbulReporter(),

      junitReporter: getJUnitReporter(),

      ngJson2JsPreprocessor: {
        stripPrefix: 'app/'
      },

      client: {
        mocha: {
          timeout: 20000
        },
        // Change this to false to hide console.logs in the karma output
        captureConsole: true
      },

      browserConsoleLogOptions: {
        level: 'log',
        terminal: true
      },

      // web server port
      port: getPort(),

      // enable / disable colors in the output (reporters and logs)
      colors: true,

      // level of logging
      // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
      logLevel: config.LOG_INFO,

      // enable / disable watching file and executing tests whenever any file changes
      autoWatch: false,

      // start these browsers
      // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
      // ChomeHeadless is a valid option
      browsers: ['PhantomJS'],

      // Continuous Integration mode
      // if true, Karma captures browsers, runs the tests and exits
      singleRun: true,

      // Report tests that take longer than 10ms to run
      reportSlowerThan: 20,

      // Increase "no activity" timeout to 100s.
      // Should help to avoid unexpected PhantomJS::DISCONNECTED errors
      // to avoid DISCONNECTED messages
      browserDisconnectTimeout: 10000,
      browserNoActivityTimeout: 15000,
      browserDisconnectTolerance: 5,

      // Webpack configuration
      webpack: getWebpackConfig(),
      webpackMiddleware: {
        colors: true,
        stats: 'errors-only'
      },
      // Don't fail with empty tests (right now, we have no tests for filters or others)
      failOnEmptyTestSuite: false,

      mime: {
        'text/x-typescript': ['ts', 'tsx']
      }
    });
  };
})();
```

**Comment by manufacturedba** [comment]
Hi @rcollette, it looks like `require('karma-promise')` is missing from `plugins` in your config.  Normally adding the framework is sufficient, but in your case, you need to explicitly tell Karma to load it.
